"""add favorites notes screenshots

Revision ID: 460faca60550
Revises: c3b7b843e049
Create Date: 2026-04-23 16:52:52.699776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460faca60550'
down_revision: Union[str, Sequence[str], None] = 'c3b7b843e049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='逻辑外键 users.id'),
    sa.Column('entry_id', sa.String(length=255), nullable=False, comment='registry 条目 ID（带斜杠）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now', '+08:00'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_id', name='uq_favorites_user_entry')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='逻辑外键 users.id'),
    sa.Column('entry_id', sa.String(length=255), nullable=False, comment='registry 条目 ID（带斜杠）'),
    sa.Column('content', sa.Text(), nullable=False, comment='markdown 源码'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now', '+08:00'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_id', name='uq_notes_user_entry')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_user_id'), ['user_id'], unique=False)

    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='逻辑外键 users.id'),
    sa.Column('entry_id', sa.String(length=255), nullable=False, comment='registry 条目 ID（带斜杠）'),
    sa.Column('object_name', sa.String(length=512), nullable=False, comment='MinIO 对象 key，如 user-1/abc.png'),
    sa.Column('url', sa.String(length=1024), nullable=False, comment='公网访问 URL'),
    sa.Column('caption', sa.String(length=512), nullable=True, comment='可选说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now', '+08:00'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenshots_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshots_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_screenshots_entry_id'))

    op.drop_table('screenshots')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_notes_entry_id'))

    op.drop_table('notes')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_entry_id'))

    op.drop_table('favorites')
    # ### end Alembic commands ###
